services:
  webapp: 
    build: ex03 # build from a Dockerfile in ex03 folder
    ports:  # the port mappings between the host machine and the container
      - "80:8501" # map host's port 80 to container's 8501
    env_file: #  specify one or more files that contain environment variables
      - ../.env 
    volumes: # specify a volume mount (VOLUME:CONTAINER_PATH), or an access mode (VOLUME:CONTAINER_PATH:ACCESS_MODE).
      - /Users/dwoodbridge/.ssh/inspired-goal-msds692-bucket.json:/tmp/gcp-key.json
  api-server:
    build: ex01 # build from a Dockerfile in ex01 folder
    ports:
      - "8000:8000"
    networks:  #  Specify which networks the containers for that service should connect to/communicate with.
      - app-network
    env_file: #  specify one or more files that contain environment variables
      - ../.env 
    volumes:
      - /Users/dwoodbridge/.ssh/inspired-goal-msds692-bucket.json:/tmp/gcp-key.json
  cron:
    build: ex05
    depends_on: # To control the order of service startup and shutdown.
      - api-server # depends on it
    networks:
      - app-network # name of the network
networks: # Networks let services communicate with each other
  # By default, services can all communicate.
  app-network: # In this case, we don't actually need extra network. 
